### ISSUE TITLE
"local_ws_enrolcohort_add_instance" 

### ISSUE THREAD

**Issue by santoshredchip** [learningworks/moodle-local_ws_enrolcohort#3]
"local_ws_enrolcohort_add_instance" function of webservices for some cohorts its working and for some cohorts its showing
Array
(
[faultCode] => 10648825
[faultString] => Object is not available at this context! | DEBUG INFO: Cohort with id 39 is not available at this context. | ERRORCODE: unavailableatcontext
)

Below is my code - 
/// SETUP - NEED TO BE CHANGED
$token = '41d74182154a8b8197d41730373faf16';
$domainname = 'http://XYZ';
$functionname = 'local_ws_enrolcohort_add_instance';

$user1 = new stdClass();
$user1->courseid  = 6;
$user1->cohortid = 37;
$user1->roleid = 5;

/// XML-RPC CALL
$serverurl = $domainname . '/webservice/xmlrpc/server.php'. '?wstoken=' . $token;
require_once('curl.php');
$curl = new curl;
$curl->setHeader('Content-type: text/xml');
$post = xmlrpc_encode_request($functionname, array($user1));
$resp = xmlrpc_decode($curl->post($serverurl, $post));
echo "<pre>";
print_r($resp);

**Comment by emyb2** [comment]
Hi Santosh,

Either there are no available cohorts at the course context or there are cohorts available but not the one specified. An easy way to check if this is expected is to try and add a cohort enrolment instance in moodle http://xyz/enrol/instance.php?id=6. If the cohort with id 37 is not available to add then this is expected. If it is then please send the course and cohort settings so I can replicate this

**Comment by emyb2** [comment]
Hi @santoshredchip 

Is this still an issue?

**Comment by jguchte** [comment]
> Hi @santoshredchip
> 
> Is this still an issue?

Hi emyb2,

I am experiencing the same issue, althoug only on our production environment. Our development evironment is working fine. We are looking for any differences between those.

We use https://xyz/webservice/rest/server.php with the following parameters:
wstoken:[token here....]
wsfunction:local_ws_enrolcohort_add_instance
moodlewsrestformat:json
instance[courseid]:1590
instance[cohortid]:318
instance[roleid]:5

On the production environment I reveive the following error:

{
    "exception": "local_ws_enrolcohort\\exceptions\\cohort_not_available_at_context_exception",
    "errorcode": "unavailableatcontext",
    "message": "Object is not available at this context!"
}

Thanks in advance!

**Comment by emyb2** [comment]
Hi @jguchte 

Can you provide any details about the cohort you are trying to add? What context is the cohort? What context is the course? Are you adding a system level cohort to a course? The only way this can happen is if you are trying to add a cohort whose parent context is not system or not the same context as the course

**Comment by jguchte** [comment]
Hi emyb2,

The cohort is created at the top (system) level. The courses are in subcategories. We do not use cohorts other then system cohorts. So yes, we are trying to add a system level cohort to a course. And, if we add the cohort manually to the course then there's no problem.

It seems the cohort is not in the list of available cohorts for the current context. See:
https://github.com/learningworks/moodle-local_ws_enrolcohort/blob/4937855a26836bc5179acd0a770f96113d6d1cb4/externallib.php#L330


Thanks in advance.

**Comment by emyb2** [comment]
Hi @jguchte 

I can't replicate this. Can you share your cohort settings, moodle version, course settings.

**Comment by thoschi** [comment]
Hi  there,

we probably found a solution to this. It is only reproducible for more than 25 cohorts within a context, as this is a hardcoded limit in `cohort_get_available_cohorts` in Moodles `cohort/lib.php`.
When calling `cohort_get_available_cohorts`, this limit has to be set to 0 to return all available cohorts.
See our commit for a new version of externallib.php: https://github.com/learningworks/moodle-local_ws_enrolcohort/pull/5/commits/389763eac7ffd3940383f45bd5807d45e7972017

_Thank you for this important addition to moodles API (which should be included in core IMHO)! We are just developing a (pythonic) script that will prepare our moodle site to start a new school year (set up all courses, sign up/enrol users, create global cohorts) and we are using your addition massively for the automatic enrolment. It saves us a lot of work!_

Thomas

**Comment by emyb** [comment]
Hi @santoshredchip 

The updated version v3.3.3 should resolve this issue assuming your production environment has more than 25 cohorts. Thanks again @thoschi for the fix.
