### ISSUE TITLE
Problem with user-deletion

### ISSUE THREAD

**Issue by thoschi** [learningworks/moodle-local_ws_enrolcohort#6]
Hello there

we use local_ws_enrolcohort when syncing our users to cohorts and into the courses by a python script (connecting to the REST API of Moodle).

While testing we also had to delete some users. For those users the GDPR-settings automatically created deletion entries, which we accepted.

From then on the cronjob did not finish any longer but failed after some time with an fatal php-error (it took us some time to find out). The messages was:

Declaration of local_ws_enrolcohort\privacy\provider::get_reason() must be compatible with core_privacy\local\metadata\null_provider::get_reason()

I have no idea if this is related but I know, when I remove the plugin, the cronjob works as it should.

Best regards
thoschi

**Comment by emyb** [comment]
Thanks. I believe this is because the function doesn't have a return type declaration as defined in the parent class. This will need to be added, but I don't have a timeframe on when that will happen.

**Comment by thoschi** [comment]
Thank you for the reply. As the workaround is quite easy (delete the plugin, start the cronjob and install it again), it is not that urgent.
It just might be helpful forf others to know if they run into the same problem.
Looking forward to a solution - whenever :-)
Thanks!
